version: '3.8' # Khai báo phiên bản Docker Compose (3.8 là bản ổn định phổ biến)

services: # Danh sách các dịch vụ cần chạy
  sqlserver_db: # Tên định danh của dịch vụ database
    image: mcr.microsoft.com/mssql/server:2022-latest # Tải bản cài đặt SQL Server 2022 từ kho ảnh chính thức
    container_name: QuizzStudyAS # Đặt tên cho container để dễ quản lý trong Docker Desktop
    ports:
      - "4000:1433" # Cổng máy thật : Cổng trong container. Cho phép app ASP.NET kết nối vào qua cổng 1433
    environment:
      - ACCEPT_EULA=Y # Bắt buộc: Chấp nhận các điều khoản sử dụng của Microsoft
      - MSSQL_SA_PASSWORD=Admin@123456 # Thiết lập mật khẩu admin (sa) cho database
    volumes:
      - db_data:/var/opt/mssql # Lưu dữ liệu vào volume để khi tắt container hoặc khởi động lại, dữ liệu không bị mất

volumes: # Khai báo vùng lưu trữ dữ liệu độc lập
  db_data: